# Write a program to accept marks om 6 students and display them in a sorted manner.
marks =[]
m0 = int(input("Enter marks:"))
marks.append(m0)
m1 = int(input("Enter marks:"))
marks.append(m1)
m2 = int(input("Enter marks:"))
marks.append(m2)
m3 = int(input("Enter marks:"))
marks.append(m3)
m4 = int(input("Enter marks:"))
marks.append(m4)
m5 = int(input("Enter marks:"))
marks.append(m5)
marks.sort()
print(marks)